# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rep_combo.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(564, 434)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_4 = QtWidgets.QWidget(Form)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(self.widget_4)
        self.label_3.setStyleSheet("font: 16pt \"Sans Serif\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.label_7 = QtWidgets.QLabel(self.widget_4)
        self.label_7.setStyleSheet("font: 16pt \"Sans Serif\";")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.label_5 = QtWidgets.QLabel(self.widget_4)
        self.label_5.setStyleSheet("font: 16pt \"Sans Serif\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.widget_4)
        self.label_6.setStyleSheet("font: 16pt \"Sans Serif\";")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 1)
        self.horizontalLayout_3.setStretch(3, 1)
        self.horizontalLayout_3.setStretch(4, 1)
        self.verticalLayout.addWidget(self.widget_4)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.st_y = QtWidgets.QComboBox(self.widget)
        self.st_y.setObjectName("st_y")
        self.horizontalLayout.addWidget(self.st_y)
        self.st_m = QtWidgets.QComboBox(self.widget)
        self.st_m.setObjectName("st_m")
        self.st_m.addItem("")
        self.st_m.addItem("")
        self.st_m.addItem("")
        self.st_m.addItem("")
        self.st_m.addItem("")
        self.st_m.addItem("")
        self.st_m.addItem("")
        self.st_m.addItem("")
        self.st_m.addItem("")
        self.st_m.addItem("")
        self.st_m.addItem("")
        self.st_m.addItem("")
        self.horizontalLayout.addWidget(self.st_m)
        self.st_d = QtWidgets.QComboBox(self.widget)
        self.st_d.setObjectName("st_d")
        self.st_d.addItem("")
        self.st_d.addItem("")
        self.st_d.addItem("")
        self.st_d.addItem("")
        self.st_d.addItem("")
        self.st_d.addItem("")
        self.st_d.addItem("")
        self.st_d.addItem("")
        self.st_d.addItem("")
        self.st_d.addItem("")
        self.st_d.addItem("")
        self.st_d.addItem("")
        self.st_d.addItem("")
        self.st_d.addItem("")
        self.st_d.addItem("")
        self.st_d.addItem("")
        self.st_d.addItem("")
        self.st_d.addItem("")
        self.st_d.addItem("")
        self.st_d.addItem("")
        self.st_d.addItem("")
        self.st_d.addItem("")
        self.st_d.addItem("")
        self.st_d.addItem("")
        self.st_d.addItem("")
        self.st_d.addItem("")
        self.st_d.addItem("")
        self.st_d.addItem("")
        self.st_d.addItem("")
        self.st_d.addItem("")
        self.st_d.addItem("")
        self.horizontalLayout.addWidget(self.st_d)
        self.st_h = QtWidgets.QComboBox(self.widget)
        self.st_h.setObjectName("st_h")
        self.st_h.addItem("")
        self.st_h.addItem("")
        self.st_h.addItem("")
        self.st_h.addItem("")
        self.st_h.addItem("")
        self.st_h.addItem("")
        self.st_h.addItem("")
        self.st_h.addItem("")
        self.st_h.addItem("")
        self.st_h.addItem("")
        self.st_h.addItem("")
        self.st_h.addItem("")
        self.st_h.addItem("")
        self.st_h.addItem("")
        self.st_h.addItem("")
        self.st_h.addItem("")
        self.st_h.addItem("")
        self.st_h.addItem("")
        self.st_h.addItem("")
        self.st_h.addItem("")
        self.st_h.addItem("")
        self.st_h.addItem("")
        self.st_h.addItem("")
        self.st_h.addItem("")
        self.horizontalLayout.addWidget(self.st_h)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.ed_y = QtWidgets.QComboBox(self.widget_2)
        self.ed_y.setObjectName("ed_y")
        self.horizontalLayout_2.addWidget(self.ed_y)
        self.ed_m = QtWidgets.QComboBox(self.widget_2)
        self.ed_m.setObjectName("ed_m")
        self.ed_m.addItem("")
        self.ed_m.addItem("")
        self.ed_m.addItem("")
        self.ed_m.addItem("")
        self.ed_m.addItem("")
        self.ed_m.addItem("")
        self.ed_m.addItem("")
        self.ed_m.addItem("")
        self.ed_m.addItem("")
        self.ed_m.addItem("")
        self.ed_m.addItem("")
        self.ed_m.addItem("")
        self.horizontalLayout_2.addWidget(self.ed_m)
        self.ed_d = QtWidgets.QComboBox(self.widget_2)
        self.ed_d.setObjectName("ed_d")
        self.ed_d.addItem("")
        self.ed_d.addItem("")
        self.ed_d.addItem("")
        self.ed_d.addItem("")
        self.ed_d.addItem("")
        self.ed_d.addItem("")
        self.ed_d.addItem("")
        self.ed_d.addItem("")
        self.ed_d.addItem("")
        self.ed_d.addItem("")
        self.ed_d.addItem("")
        self.ed_d.addItem("")
        self.ed_d.addItem("")
        self.ed_d.addItem("")
        self.ed_d.addItem("")
        self.ed_d.addItem("")
        self.ed_d.addItem("")
        self.ed_d.addItem("")
        self.ed_d.addItem("")
        self.ed_d.addItem("")
        self.ed_d.addItem("")
        self.ed_d.addItem("")
        self.ed_d.addItem("")
        self.ed_d.addItem("")
        self.ed_d.addItem("")
        self.ed_d.addItem("")
        self.ed_d.addItem("")
        self.ed_d.addItem("")
        self.ed_d.addItem("")
        self.ed_d.addItem("")
        self.ed_d.addItem("")
        self.horizontalLayout_2.addWidget(self.ed_d)
        self.ed_h = QtWidgets.QComboBox(self.widget_2)
        self.ed_h.setObjectName("ed_h")
        self.ed_h.addItem("")
        self.ed_h.addItem("")
        self.ed_h.addItem("")
        self.ed_h.addItem("")
        self.ed_h.addItem("")
        self.ed_h.addItem("")
        self.ed_h.addItem("")
        self.ed_h.addItem("")
        self.ed_h.addItem("")
        self.ed_h.addItem("")
        self.ed_h.addItem("")
        self.ed_h.addItem("")
        self.ed_h.addItem("")
        self.ed_h.addItem("")
        self.ed_h.addItem("")
        self.ed_h.addItem("")
        self.ed_h.addItem("")
        self.ed_h.addItem("")
        self.ed_h.addItem("")
        self.ed_h.addItem("")
        self.ed_h.addItem("")
        self.ed_h.addItem("")
        self.ed_h.addItem("")
        self.ed_h.addItem("")
        self.horizontalLayout_2.addWidget(self.ed_h)
        self.verticalLayout.addWidget(self.widget_2)
        self.gen_btn = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gen_btn.sizePolicy().hasHeightForWidth())
        self.gen_btn.setSizePolicy(sizePolicy)
        self.gen_btn.setStyleSheet("QPushButton{\n"
"font: 16pt \"Sans Serif\";\n"
"background-color: rgb(36,170,250);\n"
"border-radius: 5px;\n"
"color:white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(72,200,250);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(18,140,250);\n"
"}")
        self.gen_btn.setObjectName("gen_btn")
        self.verticalLayout.addWidget(self.gen_btn)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 2)
        self.verticalLayout.setStretch(2, 2)
        self.verticalLayout.setStretch(3, 1)

        self.retranslateUi(Form)
        self.gen_btn.clicked.connect(Form.gen_csv)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "YEAR"))
        self.label_7.setText(_translate("Form", "MONTH"))
        self.label_5.setText(_translate("Form", "DAY"))
        self.label_6.setText(_translate("Form", "HOUR"))
        self.label.setText(_translate("Form", "START TIME"))
        self.st_m.setItemText(0, _translate("Form", "01"))
        self.st_m.setItemText(1, _translate("Form", "02"))
        self.st_m.setItemText(2, _translate("Form", "03"))
        self.st_m.setItemText(3, _translate("Form", "04"))
        self.st_m.setItemText(4, _translate("Form", "05"))
        self.st_m.setItemText(5, _translate("Form", "06"))
        self.st_m.setItemText(6, _translate("Form", "07"))
        self.st_m.setItemText(7, _translate("Form", "08"))
        self.st_m.setItemText(8, _translate("Form", "09"))
        self.st_m.setItemText(9, _translate("Form", "10"))
        self.st_m.setItemText(10, _translate("Form", "11"))
        self.st_m.setItemText(11, _translate("Form", "12"))
        self.st_d.setItemText(0, _translate("Form", "01"))
        self.st_d.setItemText(1, _translate("Form", "02"))
        self.st_d.setItemText(2, _translate("Form", "03"))
        self.st_d.setItemText(3, _translate("Form", "04"))
        self.st_d.setItemText(4, _translate("Form", "05"))
        self.st_d.setItemText(5, _translate("Form", "06"))
        self.st_d.setItemText(6, _translate("Form", "07"))
        self.st_d.setItemText(7, _translate("Form", "08"))
        self.st_d.setItemText(8, _translate("Form", "09"))
        self.st_d.setItemText(9, _translate("Form", "10"))
        self.st_d.setItemText(10, _translate("Form", "11"))
        self.st_d.setItemText(11, _translate("Form", "12"))
        self.st_d.setItemText(12, _translate("Form", "13"))
        self.st_d.setItemText(13, _translate("Form", "14"))
        self.st_d.setItemText(14, _translate("Form", "15"))
        self.st_d.setItemText(15, _translate("Form", "16"))
        self.st_d.setItemText(16, _translate("Form", "17"))
        self.st_d.setItemText(17, _translate("Form", "18"))
        self.st_d.setItemText(18, _translate("Form", "19"))
        self.st_d.setItemText(19, _translate("Form", "20"))
        self.st_d.setItemText(20, _translate("Form", "21"))
        self.st_d.setItemText(21, _translate("Form", "22"))
        self.st_d.setItemText(22, _translate("Form", "23"))
        self.st_d.setItemText(23, _translate("Form", "24"))
        self.st_d.setItemText(24, _translate("Form", "25"))
        self.st_d.setItemText(25, _translate("Form", "26"))
        self.st_d.setItemText(26, _translate("Form", "27"))
        self.st_d.setItemText(27, _translate("Form", "28"))
        self.st_d.setItemText(28, _translate("Form", "29"))
        self.st_d.setItemText(29, _translate("Form", "30"))
        self.st_d.setItemText(30, _translate("Form", "31"))
        self.st_h.setItemText(0, _translate("Form", "00"))
        self.st_h.setItemText(1, _translate("Form", "01"))
        self.st_h.setItemText(2, _translate("Form", "02"))
        self.st_h.setItemText(3, _translate("Form", "03"))
        self.st_h.setItemText(4, _translate("Form", "04"))
        self.st_h.setItemText(5, _translate("Form", "05"))
        self.st_h.setItemText(6, _translate("Form", "06"))
        self.st_h.setItemText(7, _translate("Form", "07"))
        self.st_h.setItemText(8, _translate("Form", "08"))
        self.st_h.setItemText(9, _translate("Form", "09"))
        self.st_h.setItemText(10, _translate("Form", "10"))
        self.st_h.setItemText(11, _translate("Form", "11"))
        self.st_h.setItemText(12, _translate("Form", "12"))
        self.st_h.setItemText(13, _translate("Form", "13"))
        self.st_h.setItemText(14, _translate("Form", "14"))
        self.st_h.setItemText(15, _translate("Form", "15"))
        self.st_h.setItemText(16, _translate("Form", "16"))
        self.st_h.setItemText(17, _translate("Form", "17"))
        self.st_h.setItemText(18, _translate("Form", "18"))
        self.st_h.setItemText(19, _translate("Form", "19"))
        self.st_h.setItemText(20, _translate("Form", "20"))
        self.st_h.setItemText(21, _translate("Form", "21"))
        self.st_h.setItemText(22, _translate("Form", "22"))
        self.st_h.setItemText(23, _translate("Form", "23"))
        self.label_2.setText(_translate("Form", "END TIME"))
        self.ed_m.setItemText(0, _translate("Form", "01"))
        self.ed_m.setItemText(1, _translate("Form", "02"))
        self.ed_m.setItemText(2, _translate("Form", "03"))
        self.ed_m.setItemText(3, _translate("Form", "04"))
        self.ed_m.setItemText(4, _translate("Form", "05"))
        self.ed_m.setItemText(5, _translate("Form", "06"))
        self.ed_m.setItemText(6, _translate("Form", "07"))
        self.ed_m.setItemText(7, _translate("Form", "08"))
        self.ed_m.setItemText(8, _translate("Form", "09"))
        self.ed_m.setItemText(9, _translate("Form", "10"))
        self.ed_m.setItemText(10, _translate("Form", "11"))
        self.ed_m.setItemText(11, _translate("Form", "12"))
        self.ed_d.setItemText(0, _translate("Form", "01"))
        self.ed_d.setItemText(1, _translate("Form", "02"))
        self.ed_d.setItemText(2, _translate("Form", "03"))
        self.ed_d.setItemText(3, _translate("Form", "04"))
        self.ed_d.setItemText(4, _translate("Form", "05"))
        self.ed_d.setItemText(5, _translate("Form", "06"))
        self.ed_d.setItemText(6, _translate("Form", "07"))
        self.ed_d.setItemText(7, _translate("Form", "08"))
        self.ed_d.setItemText(8, _translate("Form", "09"))
        self.ed_d.setItemText(9, _translate("Form", "10"))
        self.ed_d.setItemText(10, _translate("Form", "11"))
        self.ed_d.setItemText(11, _translate("Form", "12"))
        self.ed_d.setItemText(12, _translate("Form", "13"))
        self.ed_d.setItemText(13, _translate("Form", "14"))
        self.ed_d.setItemText(14, _translate("Form", "15"))
        self.ed_d.setItemText(15, _translate("Form", "16"))
        self.ed_d.setItemText(16, _translate("Form", "17"))
        self.ed_d.setItemText(17, _translate("Form", "18"))
        self.ed_d.setItemText(18, _translate("Form", "19"))
        self.ed_d.setItemText(19, _translate("Form", "20"))
        self.ed_d.setItemText(20, _translate("Form", "21"))
        self.ed_d.setItemText(21, _translate("Form", "22"))
        self.ed_d.setItemText(22, _translate("Form", "23"))
        self.ed_d.setItemText(23, _translate("Form", "24"))
        self.ed_d.setItemText(24, _translate("Form", "25"))
        self.ed_d.setItemText(25, _translate("Form", "26"))
        self.ed_d.setItemText(26, _translate("Form", "27"))
        self.ed_d.setItemText(27, _translate("Form", "28"))
        self.ed_d.setItemText(28, _translate("Form", "29"))
        self.ed_d.setItemText(29, _translate("Form", "30"))
        self.ed_d.setItemText(30, _translate("Form", "31"))
        self.ed_h.setItemText(0, _translate("Form", "00"))
        self.ed_h.setItemText(1, _translate("Form", "01"))
        self.ed_h.setItemText(2, _translate("Form", "02"))
        self.ed_h.setItemText(3, _translate("Form", "03"))
        self.ed_h.setItemText(4, _translate("Form", "04"))
        self.ed_h.setItemText(5, _translate("Form", "05"))
        self.ed_h.setItemText(6, _translate("Form", "06"))
        self.ed_h.setItemText(7, _translate("Form", "07"))
        self.ed_h.setItemText(8, _translate("Form", "08"))
        self.ed_h.setItemText(9, _translate("Form", "09"))
        self.ed_h.setItemText(10, _translate("Form", "10"))
        self.ed_h.setItemText(11, _translate("Form", "11"))
        self.ed_h.setItemText(12, _translate("Form", "12"))
        self.ed_h.setItemText(13, _translate("Form", "13"))
        self.ed_h.setItemText(14, _translate("Form", "14"))
        self.ed_h.setItemText(15, _translate("Form", "15"))
        self.ed_h.setItemText(16, _translate("Form", "16"))
        self.ed_h.setItemText(17, _translate("Form", "17"))
        self.ed_h.setItemText(18, _translate("Form", "18"))
        self.ed_h.setItemText(19, _translate("Form", "19"))
        self.ed_h.setItemText(20, _translate("Form", "20"))
        self.ed_h.setItemText(21, _translate("Form", "21"))
        self.ed_h.setItemText(22, _translate("Form", "22"))
        self.ed_h.setItemText(23, _translate("Form", "23"))
        self.gen_btn.setText(_translate("Form", "GENERATE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
